// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzD4HbzX-HgGtJ4hiSEqK4sIJ4jfcOX8',
    appId: '1:334736433219:web:084ed0fac89fce099bf4f6',
    messagingSenderId: '334736433219',
    projectId: 'instagram-flutter-5e6ad',
    authDomain: 'instagram-flutter-5e6ad.firebaseapp.com',
    storageBucket: 'instagram-flutter-5e6ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Tp6Ro7eib1ZDw2dT1vUF4jt_ZmotF10',
    appId: '1:334736433219:android:11f01101427fbe079bf4f6',
    messagingSenderId: '334736433219',
    projectId: 'instagram-flutter-5e6ad',
    storageBucket: 'instagram-flutter-5e6ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsRvXAZxoxtfoGviO_ew2cOYIZaGXj41w',
    appId: '1:334736433219:ios:360635f7ebf951c99bf4f6',
    messagingSenderId: '334736433219',
    projectId: 'instagram-flutter-5e6ad',
    storageBucket: 'instagram-flutter-5e6ad.appspot.com',
    iosClientId: '334736433219-bfquien8u8b2ggg1qp3dq7qat07js4m7.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsRvXAZxoxtfoGviO_ew2cOYIZaGXj41w',
    appId: '1:334736433219:ios:360635f7ebf951c99bf4f6',
    messagingSenderId: '334736433219',
    projectId: 'instagram-flutter-5e6ad',
    storageBucket: 'instagram-flutter-5e6ad.appspot.com',
    iosClientId: '334736433219-bfquien8u8b2ggg1qp3dq7qat07js4m7.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );
}
